// GEOPULSE QUIZ BANK — V2.2
// 50 bilingual questions across 4 categories
// Types: knowledge (MC), identify (map zoom + MC), locate (click map)
const QUIZ_BANK = {
geopolitics: [
{id:"geo_001",type:"knowledge",difficulty:"easy",
question:{en:"Which strait connects the Mediterranean and the Atlantic?",de:"Welche Meerenge verbindet Mittelmeer und Atlantik?"},
choices:[
{text:{en:"Strait of Gibraltar",de:"Straße von Gibraltar"},correct:true},
{text:{en:"Strait of Hormuz",de:"Straße von Hormus"},correct:false},
{text:{en:"Strait of Malacca",de:"Straße von Malakka"},correct:false},
{text:{en:"Bosphorus",de:"Bosporus"},correct:false}],
mapView:{center:[-5.6,35.9],zoom:8},
explanation:{en:"The Strait of Gibraltar is only 14 km wide at its narrowest point.",de:"Die Straße von Gibraltar ist an der engsten Stelle nur 14 km breit."},
relatedTour:"chokepoints"},
{id:"geo_002",type:"knowledge",difficulty:"medium",
question:{en:"How much of global trade passes through the Suez Canal?",de:"Wie viel des Welthandels passiert den Suezkanal?"},
choices:[
{text:{en:"~12-15% of global trade",de:"~12-15% des Welthandels"},correct:true},
{text:{en:"~5% of global trade",de:"~5% des Welthandels"},correct:false},
{text:{en:"~30% of global trade",de:"~30% des Welthandels"},correct:false},
{text:{en:"~1% of global trade",de:"~1% des Welthandels"},correct:false}],
mapView:{center:[33,28],zoom:5},
explanation:{en:"The Suez Canal connects the Mediterranean to the Red Sea.",de:"Der Suezkanal verbindet das Mittelmeer mit dem Roten Meer."},
relatedTour:"chokepoints"},
{id:"geo_003",type:"identify",difficulty:"medium",
question:{en:"The map shows a strait. Which water passage is this?",de:"Die Karte zeigt eine Meerenge. Welche ist es?"},
choices:[
{text:{en:"Strait of Hormuz",de:"Straße von Hormus"},correct:true},
{text:{en:"Strait of Malacca",de:"Straße von Malakka"},correct:false},
{text:{en:"Taiwan Strait",de:"Taiwanstraße"},correct:false},
{text:{en:"Strait of Gibraltar",de:"Straße von Gibraltar"},correct:false}],
mapView:{center:[56.3,26.6],zoom:9},
explanation:{en:"~30% of global seaborne oil passes through Hormuz.",de:"~30% des weltweiten Seehandels-Öls passiert Hormus."},
relatedTour:"chokepoints"},
{id:"geo_004",type:"knowledge",difficulty:"easy",
question:{en:"Which country is NOT a BRICS member?",de:"Welches Land ist KEIN BRICS-Mitglied?"},
choices:[
{text:{en:"Mexico",de:"Mexiko"},correct:true},
{text:{en:"India",de:"Indien"},correct:false},
{text:{en:"Brazil",de:"Brasilien"},correct:false},
{text:{en:"South Africa",de:"Südafrika"},correct:false}],
mapView:{center:[20,10],zoom:2},
explanation:{en:"BRICS = Brazil, Russia, India, China, South Africa + new members since 2024.",de:"BRICS = Brasilien, Russland, Indien, China, Südafrika + neue Mitglieder seit 2024."},
relatedTour:"bri"},
{id:"geo_005",type:"knowledge",difficulty:"hard",
question:{en:"China's Belt & Road Initiative primarily finances what?",de:"Chinas Seidenstraßen-Initiative finanziert hauptsächlich was?"},
choices:[
{text:{en:"Infrastructure in developing nations",de:"Infrastruktur in Entwicklungsländern"},correct:true},
{text:{en:"Military bases worldwide",de:"Militärbasen weltweit"},correct:false},
{text:{en:"Space exploration programs",de:"Weltraumforschungsprogramme"},correct:false},
{text:{en:"European Union projects",de:"EU-Projekte"},correct:false}],
mapView:{center:[80,35],zoom:3},
explanation:{en:"BRI invests in ports, railways, and roads across 140+ countries.",de:"BRI investiert in Häfen, Eisenbahnen und Straßen in über 140 Ländern."},
relatedTour:"bri"},
{id:"geo_006",type:"identify",difficulty:"hard",
question:{en:"The map shows a major shipping strait between two landmasses. Which strait is this?",de:"Die Karte zeigt eine wichtige Schifffahrtsstraße. Welche Meerenge ist das?"},
choices:[
{text:{en:"Strait of Malacca",de:"Straße von Malakka"},correct:true},
{text:{en:"Sunda Strait",de:"Sundastraße"},correct:false},
{text:{en:"Strait of Hormuz",de:"Straße von Hormus"},correct:false},
{text:{en:"Lombok Strait",de:"Lombokstraße"},correct:false}],
mapView:{center:[101.5,2.5],zoom:6},
explanation:{en:"The Malacca Strait handles 25% of all global shipping.",de:"Die Straße von Malakka wickelt 25% des weltweiten Seehandels ab."},
relatedTour:"chokepoints"},
{id:"geo_007",type:"identify",difficulty:"easy",
question:{en:"The map shows a divided city. Which city had a famous wall?",de:"Die Karte zeigt eine geteilte Stadt. Welche Stadt hatte eine berühmte Mauer?"},
choices:[
{text:{en:"Berlin",de:"Berlin"},correct:true},
{text:{en:"Vienna",de:"Wien"},correct:false},
{text:{en:"Prague",de:"Prag"},correct:false},
{text:{en:"Warsaw",de:"Warschau"},correct:false}],
mapView:{center:[13.4,52.52],zoom:8},
explanation:{en:"The Berlin Wall divided the city from 1961-1989.",de:"Die Berliner Mauer teilte die Stadt von 1961-1989."},
relatedTour:"coldwar"},
{id:"geo_008",type:"knowledge",difficulty:"medium",
question:{en:"How many member states does NATO currently have?",de:"Wie viele Mitgliedstaaten hat die NATO derzeit?"},
choices:[
{text:{en:"32",de:"32"},correct:true},
{text:{en:"28",de:"28"},correct:false},
{text:{en:"30",de:"30"},correct:false},
{text:{en:"35",de:"35"},correct:false}],
mapView:{center:[-10,50],zoom:3},
explanation:{en:"NATO expanded to 32 members after Finland (2023) and Sweden (2024) joined.",de:"Die NATO wuchs auf 32 Mitglieder nach dem Beitritt Finnlands (2023) und Schwedens (2024)."},
relatedTour:"nato"},
{id:"geo_009",type:"identify",difficulty:"hard",
question:{en:"The map shows a disputed strait. Which flashpoint is this?",de:"Die Karte zeigt eine umstrittene Meerenge. Welcher Krisenherd ist das?"},
choices:[
{text:{en:"Taiwan Strait",de:"Taiwanstraße"},correct:true},
{text:{en:"Strait of Hormuz",de:"Straße von Hormus"},correct:false},
{text:{en:"Korea Strait",de:"Koreastraße"},correct:false},
{text:{en:"Strait of Malacca",de:"Straße von Malakka"},correct:false}],
mapView:{center:[120,24],zoom:7},
explanation:{en:"The Taiwan Strait is one of the world's most sensitive geopolitical flashpoints.",de:"Die Taiwanstraße ist einer der sensibelsten geopolitischen Krisenherde der Welt."},
relatedTour:"taiwan"},
{id:"geo_010",type:"locate",difficulty:"medium",
question:{en:"Click on the Korean DMZ (Demilitarized Zone).",de:"Klicke auf die koreanische DMZ (Entmilitarisierte Zone)."},
target:[126.98,37.95],mapView:{center:[127,36],zoom:5},
explanation:{en:"The Korean DMZ is 250 km long and 4 km wide, separating North and South Korea since 1953.",de:"Die koreanische DMZ ist 250 km lang und 4 km breit und trennt Nord- und Südkorea seit 1953."},
relatedTour:"forbiddenzones"},
{id:"geo_011",type:"knowledge",difficulty:"hard",
question:{en:"Which country has the most nuclear warheads?",de:"Welches Land hat die meisten Atomsprengköpfe?"},
choices:[
{text:{en:"Russia (~5,580)",de:"Russland (~5.580)"},correct:true},
{text:{en:"United States (~5,044)",de:"USA (~5.044)"},correct:false},
{text:{en:"China (~500)",de:"China (~500)"},correct:false},
{text:{en:"France (~290)",de:"Frankreich (~290)"},correct:false}],
mapView:{center:[60,55],zoom:3},
explanation:{en:"Russia and the US hold ~90% of the world's nuclear weapons combined.",de:"Russland und die USA besitzen zusammen ~90% der weltweiten Atomwaffen."},
relatedTour:"nuclear"},
{id:"geo_012",type:"locate",difficulty:"easy",
question:{en:"Click on the Panama Canal.",de:"Klicke auf den Panamakanal."},
target:[-79.9,9.1],mapView:{center:[-78,12],zoom:4},
explanation:{en:"The Panama Canal connects the Atlantic and Pacific Oceans, saving ships a 12,000 km journey.",de:"Der Panamakanal verbindet Atlantik und Pazifik und spart Schiffen 12.000 km Umweg."},
relatedTour:"chokepoints"},
{id:"geo_013",type:"knowledge",difficulty:"medium",
question:{en:"Which 5 countries are permanent UN Security Council members?",de:"Welche 5 Länder sind ständige Mitglieder des UN-Sicherheitsrats?"},
choices:[
{text:{en:"USA, Russia, China, UK, France",de:"USA, Russland, China, UK, Frankreich"},correct:true},
{text:{en:"USA, Russia, China, Germany, Japan",de:"USA, Russland, China, Deutschland, Japan"},correct:false},
{text:{en:"USA, Russia, China, India, Brazil",de:"USA, Russland, China, Indien, Brasilien"},correct:false},
{text:{en:"USA, Russia, UK, France, Germany",de:"USA, Russland, UK, Frankreich, Deutschland"},correct:false}],
mapView:{center:[-73.97,40.75],zoom:10},
explanation:{en:"The P5 have held veto power since the UN was founded in 1945.",de:"Die P5 haben seit der Gründung der UN 1945 Vetorecht."},
relatedTour:"bri"}
],
history: [
{id:"his_001",type:"knowledge",difficulty:"easy",
question:{en:"In which year did World War II end in Europe?",de:"In welchem Jahr endete der Zweite Weltkrieg in Europa?"},
choices:[
{text:{en:"1945",de:"1945"},correct:true},
{text:{en:"1944",de:"1944"},correct:false},
{text:{en:"1946",de:"1946"},correct:false},
{text:{en:"1943",de:"1943"},correct:false}],
mapView:{center:[13.4,52.5],zoom:5},
explanation:{en:"Germany surrendered on May 8, 1945 — Victory in Europe Day.",de:"Deutschland kapitulierte am 8. Mai 1945 — Tag der Befreiung."},
relatedTour:"ww2"},
{id:"his_002",type:"identify",difficulty:"medium",
question:{en:"The map shows an ancient city. Which empire built the Colosseum here?",de:"Die Karte zeigt eine antike Stadt. Welches Reich baute hier das Kolosseum?"},
choices:[
{text:{en:"Roman Empire",de:"Römisches Reich"},correct:true},
{text:{en:"Ottoman Empire",de:"Osmanisches Reich"},correct:false},
{text:{en:"Byzantine Empire",de:"Byzantinisches Reich"},correct:false},
{text:{en:"Persian Empire",de:"Persisches Reich"},correct:false}],
mapView:{center:[12.49,41.89],zoom:10},
explanation:{en:"The Colosseum was built 70-80 AD and held 50,000 spectators.",de:"Das Kolosseum wurde 70-80 n.Chr. erbaut und fasste 50.000 Zuschauer."},
relatedTour:"romanempire"},
{id:"his_003",type:"knowledge",difficulty:"medium",
question:{en:"How many passengers and crew died when the Titanic sank in 1912?",de:"Wie viele Passagiere und Besatzungsmitglieder starben beim Untergang der Titanic 1912?"},
choices:[
{text:{en:"~1,500",de:"~1.500"},correct:true},
{text:{en:"~800",de:"~800"},correct:false},
{text:{en:"~2,200",de:"~2.200"},correct:false},
{text:{en:"~500",de:"~500"},correct:false}],
mapView:{center:[-40,45],zoom:3},
explanation:{en:"The Titanic sank on April 15, 1912, about 600 km south of Newfoundland.",de:"Die Titanic sank am 15. April 1912, etwa 600 km südlich von Neufundland."},
relatedTour:"shipwrecks"},
{id:"his_004",type:"knowledge",difficulty:"easy",
question:{en:"Which battle is considered the turning point of WW2 in Europe?",de:"Welche Schlacht gilt als Wendepunkt des 2. Weltkriegs in Europa?"},
choices:[
{text:{en:"Battle of Stalingrad",de:"Schlacht von Stalingrad"},correct:true},
{text:{en:"Battle of Britain",de:"Luftschlacht um England"},correct:false},
{text:{en:"D-Day Normandy",de:"D-Day Normandie"},correct:false},
{text:{en:"Battle of the Bulge",de:"Ardennenoffensive"},correct:false}],
mapView:{center:[44.5,48.7],zoom:8},
explanation:{en:"Stalingrad (1942-43) was the deadliest battle in history with ~2 million casualties.",de:"Stalingrad (1942-43) war die verlustreichste Schlacht der Geschichte mit ~2 Mio. Opfern."},
relatedTour:"ww2"},
{id:"his_005",type:"knowledge",difficulty:"hard",
question:{en:"Which ancient wonder was located in Alexandria, Egypt?",de:"Welches antike Weltwunder befand sich in Alexandria, Ägypten?"},
choices:[
{text:{en:"Lighthouse of Alexandria",de:"Leuchtturm von Alexandria"},correct:true},
{text:{en:"Colossus of Rhodes",de:"Koloss von Rhodos"},correct:false},
{text:{en:"Hanging Gardens",de:"Hängende Gärten"},correct:false},
{text:{en:"Temple of Artemis",de:"Tempel der Artemis"},correct:false}],
mapView:{center:[29.92,31.2],zoom:11},
explanation:{en:"The Pharos lighthouse was ~130m tall, one of the tallest structures for centuries.",de:"Der Pharos-Leuchtturm war ~130m hoch, jahrhundertelang eines der höchsten Bauwerke."},
relatedTour:"lostwonders"},
{id:"his_006",type:"identify",difficulty:"medium",
question:{en:"The map shows a location. What was signed here in 1919?",de:"Die Karte zeigt einen Ort. Was wurde hier 1919 unterzeichnet?"},
choices:[
{text:{en:"Treaty of Versailles",de:"Vertrag von Versailles"},correct:true},
{text:{en:"Treaty of Vienna",de:"Wiener Kongress"},correct:false},
{text:{en:"Treaty of Westphalia",de:"Westfälischer Frieden"},correct:false},
{text:{en:"Treaty of Tordesillas",de:"Vertrag von Tordesillas"},correct:false}],
mapView:{center:[2.12,48.8],zoom:9},
explanation:{en:"The Treaty of Versailles ended WWI and reshaped Europe's borders.",de:"Der Vertrag von Versailles beendete den 1. Weltkrieg und veränderte Europas Grenzen."},
relatedTour:"ww1"},
{id:"his_007",type:"locate",difficulty:"easy",
question:{en:"Click on the map where D-Day landings took place (1944).",de:"Klicke auf die Karte, wo die D-Day-Landung stattfand (1944)."},
target:[-0.86,49.35],mapView:{center:[-2,48],zoom:5},
explanation:{en:"On June 6, 1944, Allied forces landed on Normandy beaches — the largest seaborne invasion in history.",de:"Am 6. Juni 1944 landeten die Alliierten an den Stränden der Normandie — die größte Seelandung der Geschichte."},
relatedTour:"ww2"},
{id:"his_008",type:"identify",difficulty:"hard",
question:{en:"The map shows ancient ruins in the Andes. What is this site?",de:"Die Karte zeigt antike Ruinen in den Anden. Was ist diese Stätte?"},
choices:[
{text:{en:"Machu Picchu",de:"Machu Picchu"},correct:true},
{text:{en:"Chichen Itza",de:"Chichen Itza"},correct:false},
{text:{en:"Teotihuacan",de:"Teotihuacan"},correct:false},
{text:{en:"Nazca Lines",de:"Nazca-Linien"},correct:false}],
mapView:{center:[-72.545,-13.163],zoom:10},
explanation:{en:"Machu Picchu was built by the Inca in the 15th century at 2,430m altitude.",de:"Machu Picchu wurde im 15. Jahrhundert von den Inka auf 2.430m Höhe erbaut."},
relatedTour:"lostwonders"},
{id:"his_009",type:"identify",difficulty:"medium",
question:{en:"The map shows a Hawaiian naval base. What happened here on December 7, 1941?",de:"Die Karte zeigt einen hawaiianischen Marinestützpunkt. Was geschah hier am 7. Dezember 1941?"},
choices:[
{text:{en:"Japanese surprise attack on Pearl Harbor",de:"Japanischer Überraschungsangriff auf Pearl Harbor"},correct:true},
{text:{en:"US nuclear weapons test",de:"US-Atomwaffentest"},correct:false},
{text:{en:"Battle of Midway",de:"Schlacht von Midway"},correct:false},
{text:{en:"Signing of Japanese surrender",de:"Unterzeichnung der japanischen Kapitulation"},correct:false}],
mapView:{center:[-157.95,21.35],zoom:9},
explanation:{en:"Japan's surprise attack on Pearl Harbor on Dec 7, 1941 brought the US into WW2.",de:"Japans Überraschungsangriff auf Pearl Harbor am 7.12.1941 brachte die USA in den 2. Weltkrieg."},
relatedTour:"ww2"},
{id:"his_010",type:"knowledge",difficulty:"easy",
question:{en:"How long is the Great Wall of China?",de:"Wie lang ist die Chinesische Mauer?"},
choices:[
{text:{en:"~21,000 km (all sections)",de:"~21.000 km (alle Abschnitte)"},correct:true},
{text:{en:"~5,000 km",de:"~5.000 km"},correct:false},
{text:{en:"~10,000 km",de:"~10.000 km"},correct:false},
{text:{en:"~2,500 km",de:"~2.500 km"},correct:false}],
mapView:{center:[116.57,40.43],zoom:8},
explanation:{en:"Including all branches, the Wall stretches over 21,000 km across northern China.",de:"Einschließlich aller Abzweigungen erstreckt sich die Mauer über 21.000 km in Nordchina."},
relatedTour:"lostwonders"},
{id:"his_011",type:"identify",difficulty:"medium",
question:{en:"The map shows an ancient city buried by a volcano in 79 AD. Which city?",de:"Die Karte zeigt eine antike Stadt, die 79 n.Chr. von einem Vulkan verschüttet wurde. Welche Stadt?"},
choices:[
{text:{en:"Pompeii",de:"Pompeji"},correct:true},
{text:{en:"Herculaneum",de:"Herculaneum"},correct:false},
{text:{en:"Troy",de:"Troja"},correct:false},
{text:{en:"Carthage",de:"Karthago"},correct:false}],
mapView:{center:[14.49,40.75],zoom:10},
explanation:{en:"Mount Vesuvius buried Pompeii under 6m of volcanic ash, preserving it for 2,000 years.",de:"Der Vesuv begrub Pompeji unter 6m Vulkanasche und bewahrte es 2.000 Jahre lang."},
relatedTour:"lostwonders"},
{id:"his_012",type:"locate",difficulty:"hard",
question:{en:"Click where the first atomic bomb was dropped (August 6, 1945).",de:"Klicke, wo die erste Atombombe abgeworfen wurde (6. August 1945)."},
target:[132.45,34.39],mapView:{center:[135,35],zoom:4},
explanation:{en:"'Little Boy' was dropped on Hiroshima, killing ~80,000 instantly. Nagasaki followed 3 days later.",de:"'Little Boy' wurde auf Hiroshima abgeworfen und tötete sofort ~80.000 Menschen. Nagasaki folgte 3 Tage später."},
relatedTour:"nuclear"}
],
science: [
{id:"sci_001",type:"knowledge",difficulty:"easy",
question:{en:"What does the Ring of Fire refer to?",de:"Was bezeichnet der Feuerring?"},
choices:[
{text:{en:"A zone of frequent earthquakes and volcanoes around the Pacific",de:"Eine Zone häufiger Erdbeben und Vulkane rund um den Pazifik"},correct:true},
{text:{en:"A solar phenomenon",de:"Ein Sonnenphänomen"},correct:false},
{text:{en:"A wildfire belt in Africa",de:"Ein Waldbrandgürtel in Afrika"},correct:false},
{text:{en:"A deep ocean trench",de:"Ein Tiefsee-Graben"},correct:false}],
mapView:{center:[170,-5],zoom:2},
explanation:{en:"The Ring of Fire hosts 75% of the world's active volcanoes.",de:"Der Feuerring beherbergt 75% der weltweit aktiven Vulkane."},
relatedTour:"ringoffire"},
{id:"sci_002",type:"locate",difficulty:"medium",
question:{en:"Click on the map where Chernobyl is located.",de:"Klicke auf die Karte, wo sich Tschernobyl befindet."},
target:[30.1,51.39],mapView:{center:[32,50],zoom:5},
explanation:{en:"The 1986 Chernobyl disaster remains the worst nuclear accident in history.",de:"Die Tschernobyl-Katastrophe 1986 bleibt der schlimmste Atomunfall der Geschichte."},
relatedTour:"nuclear"},
{id:"sci_003",type:"identify",difficulty:"hard",
question:{en:"The map shows a crater. What caused this impact ~66 million years ago?",de:"Die Karte zeigt einen Krater. Was verursachte diesen Einschlag vor ~66 Mio. Jahren?"},
choices:[
{text:{en:"Chicxulub asteroid (dinosaur extinction)",de:"Chicxulub-Asteroid (Dinosaurier-Aussterben)"},correct:true},
{text:{en:"Tunguska event",de:"Tunguska-Ereignis"},correct:false},
{text:{en:"Meteor Crater Arizona",de:"Meteor-Krater Arizona"},correct:false},
{text:{en:"Vredefort impact",de:"Vredefort-Einschlag"},correct:false}],
mapView:{center:[-89.5,21.3],zoom:8},
explanation:{en:"The Chicxulub impact ended the age of dinosaurs and left a 180 km crater.",de:"Der Chicxulub-Einschlag beendete das Zeitalter der Dinosaurier und hinterließ einen 180 km Krater."},
relatedTour:"cosmicimpacts"},
{id:"sci_004",type:"knowledge",difficulty:"easy",
question:{en:"What causes the Northern Lights (Aurora Borealis)?",de:"Was verursacht Nordlichter (Aurora Borealis)?"},
choices:[
{text:{en:"Solar particles hitting Earth's atmosphere",de:"Sonnenpartikel treffen auf die Erdatmosphäre"},correct:true},
{text:{en:"Reflection of moonlight on ice",de:"Reflexion von Mondlicht auf Eis"},correct:false},
{text:{en:"Volcanic gases in the sky",de:"Vulkanische Gase am Himmel"},correct:false},
{text:{en:"Bioluminescent clouds",de:"Biolumineszente Wolken"},correct:false}],
mapView:{center:[25,68],zoom:3},
explanation:{en:"Solar wind particles excite gases in the upper atmosphere, creating colorful light.",de:"Sonnenwinde regen Gase in der oberen Atmosphäre an und erzeugen farbiges Licht."},
relatedTour:"aurorahunters"},
{id:"sci_005",type:"knowledge",difficulty:"easy",
question:{en:"On which border does Mount Everest sit?",de:"An welcher Grenze liegt der Mount Everest?"},
choices:[
{text:{en:"Nepal and China (Tibet)",de:"Nepal und China (Tibet)"},correct:true},
{text:{en:"India and Nepal",de:"Indien und Nepal"},correct:false},
{text:{en:"India and China",de:"Indien und China"},correct:false},
{text:{en:"Pakistan and China",de:"Pakistan und China"},correct:false}],
mapView:{center:[86.9,27.99],zoom:7},
explanation:{en:"Mount Everest is 8,849m — the highest point on Earth.",de:"Der Mount Everest ist 8.849m — der höchste Punkt der Erde."},
relatedTour:"extremeearth"},
{id:"sci_006",type:"knowledge",difficulty:"medium",
question:{en:"Which ocean current keeps Western Europe warmer than expected?",de:"Welche Meeresströmung hält Westeuropa wärmer als erwartet?"},
choices:[
{text:{en:"Gulf Stream",de:"Golfstrom"},correct:true},
{text:{en:"Kuroshio Current",de:"Kuroshio-Strom"},correct:false},
{text:{en:"Antarctic Circumpolar Current",de:"Antarktischer Zirkumpolarstrom"},correct:false},
{text:{en:"Humboldt Current",de:"Humboldt-Strom"},correct:false}],
mapView:{center:[-30,40],zoom:3},
explanation:{en:"The Gulf Stream carries warm water from the Caribbean across the Atlantic.",de:"Der Golfstrom transportiert warmes Wasser aus der Karibik über den Atlantik."},
relatedTour:"climatecrisis"},
{id:"sci_007",type:"knowledge",difficulty:"easy",
question:{en:"At what altitude does the ISS orbit Earth?",de:"In welcher Höhe umkreist die ISS die Erde?"},
choices:[
{text:{en:"~400 km",de:"~400 km"},correct:true},
{text:{en:"~100 km",de:"~100 km"},correct:false},
{text:{en:"~1,000 km",de:"~1.000 km"},correct:false},
{text:{en:"~36,000 km",de:"~36.000 km"},correct:false}],
mapView:{center:[0,20],zoom:1},
explanation:{en:"The ISS orbits at ~400 km, completing one orbit every 90 minutes at 28,000 km/h.",de:"Die ISS umkreist die Erde in ~400 km Höhe und braucht 90 Minuten pro Umlauf bei 28.000 km/h."},
relatedTour:"spacerace"},
{id:"sci_008",type:"locate",difficulty:"hard",
question:{en:"Click on the Mariana Trench — the deepest point on Earth.",de:"Klicke auf den Marianengraben — den tiefsten Punkt der Erde."},
target:[142.2,11.35],mapView:{center:[145,15],zoom:3},
explanation:{en:"The Challenger Deep in the Mariana Trench reaches 10,994m — deeper than Everest is tall.",de:"Das Challengertief im Marianengraben erreicht 10.994m — tiefer als der Everest hoch ist."},
relatedTour:"extremeearth"},
{id:"sci_009",type:"knowledge",difficulty:"medium",
question:{en:"Which desert is the largest hot desert on Earth?",de:"Welche Wüste ist die größte Heißwüste der Erde?"},
choices:[
{text:{en:"Sahara (9.2 million km²)",de:"Sahara (9,2 Mio. km²)"},correct:true},
{text:{en:"Arabian Desert (2.3 million km²)",de:"Arabische Wüste (2,3 Mio. km²)"},correct:false},
{text:{en:"Gobi Desert (1.3 million km²)",de:"Wüste Gobi (1,3 Mio. km²)"},correct:false},
{text:{en:"Kalahari (0.9 million km²)",de:"Kalahari (0,9 Mio. km²)"},correct:false}],
mapView:{center:[10,23],zoom:3},
explanation:{en:"The Sahara is roughly the size of the entire United States.",de:"Die Sahara ist ungefähr so groß wie die gesamten USA."},
relatedTour:"climatecrisis"},
{id:"sci_010",type:"knowledge",difficulty:"medium",
question:{en:"What natural disaster triggered the Fukushima nuclear meltdown in 2011?",de:"Welche Naturkatastrophe löste die Kernschmelze in Fukushima 2011 aus?"},
choices:[
{text:{en:"A 9.0 earthquake and tsunami",de:"Ein Erdbeben der Stärke 9,0 und ein Tsunami"},correct:true},
{text:{en:"A typhoon",de:"Ein Taifun"},correct:false},
{text:{en:"A volcanic eruption",de:"Ein Vulkanausbruch"},correct:false},
{text:{en:"A cyberattack on cooling systems",de:"Ein Cyberangriff auf Kühlsysteme"},correct:false}],
mapView:{center:[141,37.4],zoom:7},
explanation:{en:"A 9.0 earthquake and tsunami caused 3 reactor meltdowns at Fukushima Daiichi.",de:"Ein Erdbeben der Stärke 9,0 und ein Tsunami verursachten 3 Kernschmelzen in Fukushima Daiichi."},
relatedTour:"nuclear"},
{id:"sci_011",type:"identify",difficulty:"medium",
question:{en:"The map shows a massive volcanic caldera. Which supervolcano is this?",de:"Die Karte zeigt eine massive Vulkan-Caldera. Welcher Supervulkan ist das?"},
choices:[
{text:{en:"Yellowstone",de:"Yellowstone"},correct:true},
{text:{en:"Mount Tambora",de:"Mount Tambora"},correct:false},
{text:{en:"Toba",de:"Toba"},correct:false},
{text:{en:"Campi Flegrei",de:"Phlegräische Felder"},correct:false}],
mapView:{center:[-110.58,44.46],zoom:9},
explanation:{en:"Yellowstone's caldera is 72 km long. Its last super-eruption was 640,000 years ago.",de:"Yellowstones Caldera ist 72 km lang. Der letzte Superausbruch war vor 640.000 Jahren."},
relatedTour:"ringoffire"},
{id:"sci_012",type:"knowledge",difficulty:"hard",
question:{en:"Which tectonic plate is the largest?",de:"Welche tektonische Platte ist die größte?"},
choices:[
{text:{en:"Pacific Plate",de:"Pazifische Platte"},correct:true},
{text:{en:"North American Plate",de:"Nordamerikanische Platte"},correct:false},
{text:{en:"Eurasian Plate",de:"Eurasische Platte"},correct:false},
{text:{en:"African Plate",de:"Afrikanische Platte"},correct:false}],
mapView:{center:[-150,-10],zoom:2},
explanation:{en:"The Pacific Plate covers ~103 million km² — the largest of all tectonic plates.",de:"Die Pazifische Platte bedeckt ~103 Mio. km² — die größte aller tektonischen Platten."},
relatedTour:"ringoffire"},
{id:"sci_013",type:"identify",difficulty:"easy",
question:{en:"The map shows Antarctica. What atmospheric phenomenon was discovered here in 1985?",de:"Die Karte zeigt die Antarktis. Welches atmosphärische Phänomen wurde hier 1985 entdeckt?"},
choices:[
{text:{en:"Ozone hole",de:"Ozonloch"},correct:true},
{text:{en:"Polar vortex",de:"Polarwirbel"},correct:false},
{text:{en:"Aurora Australis",de:"Aurora Australis"},correct:false},
{text:{en:"Magnetic reversal",de:"Magnetfeldumkehr"},correct:false}],
mapView:{center:[0,-82],zoom:2},
explanation:{en:"The ozone hole led to the Montreal Protocol (1987), one of the most successful environmental treaties.",de:"Das Ozonloch führte zum Montreal-Protokoll (1987), einem der erfolgreichsten Umweltabkommen."},
relatedTour:"climatecrisis"}
],
sports: [
{id:"spo_001",type:"knowledge",difficulty:"easy",
question:{en:"In which city were the first modern Olympic Games held (1896)?",de:"In welcher Stadt fanden die ersten modernen Olympischen Spiele statt (1896)?"},
choices:[
{text:{en:"Athens",de:"Athen"},correct:true},
{text:{en:"Paris",de:"Paris"},correct:false},
{text:{en:"London",de:"London"},correct:false},
{text:{en:"Rome",de:"Rom"},correct:false}],
mapView:{center:[23.73,37.97],zoom:11},
explanation:{en:"Pierre de Coubertin revived the Olympics in Athens, Greece in 1896.",de:"Pierre de Coubertin belebte die Olympischen Spiele 1896 in Athen, Griechenland, wieder."},
relatedTour:"olympics"},
{id:"spo_002",type:"identify",difficulty:"medium",
question:{en:"The map shows a famous racing circuit. Which Grand Prix is held here?",de:"Die Karte zeigt eine berühmte Rennstrecke. Welcher Grand Prix findet hier statt?"},
choices:[
{text:{en:"Monaco Grand Prix",de:"Großer Preis von Monaco"},correct:true},
{text:{en:"Italian Grand Prix",de:"Großer Preis von Italien"},correct:false},
{text:{en:"Spanish Grand Prix",de:"Großer Preis von Spanien"},correct:false},
{text:{en:"French Grand Prix",de:"Großer Preis von Frankreich"},correct:false}],
mapView:{center:[7.42,43.73],zoom:10},
explanation:{en:"Monaco's street circuit is F1's most prestigious and glamorous race.",de:"Monacos Straßenkurs ist das prestigeträchtigste Rennen der Formel 1."},
relatedTour:"f1"},
{id:"spo_003",type:"locate",difficulty:"medium",
question:{en:"Click on the map where the 2014 FIFA World Cup was held.",de:"Klicke auf die Karte, wo die FIFA WM 2014 stattfand."},
target:[-43.17,-22.91],mapView:{center:[-50,-10],zoom:3},
explanation:{en:"Brazil hosted the 2014 World Cup, won by Germany 1-0 vs Argentina.",de:"Brasilien war Gastgeber der WM 2014, gewonnen von Deutschland 1:0 gegen Argentinien."},
relatedTour:"worldcup"},
{id:"spo_004",type:"knowledge",difficulty:"easy",
question:{en:"Which mountain is the highest of the 14 eight-thousanders?",de:"Welcher Berg ist der höchste der 14 Achttausender?"},
choices:[
{text:{en:"Mount Everest (8,849m)",de:"Mount Everest (8.849m)"},correct:true},
{text:{en:"K2 (8,611m)",de:"K2 (8.611m)"},correct:false},
{text:{en:"Kangchenjunga (8,586m)",de:"Kangchenjunga (8.586m)"},correct:false},
{text:{en:"Annapurna (8,091m)",de:"Annapurna (8.091m)"},correct:false}],
mapView:{center:[86.9,27.99],zoom:8},
explanation:{en:"Mount Everest was first summited by Hillary and Tenzing in 1953.",de:"Der Mount Everest wurde 1953 erstmals von Hillary und Tenzing bestiegen."},
relatedTour:"summits14"},
{id:"spo_005",type:"knowledge",difficulty:"medium",
question:{en:"Woodstock festival (1969) took place in which US state?",de:"Das Woodstock-Festival (1969) fand in welchem US-Bundesstaat statt?"},
choices:[
{text:{en:"New York",de:"New York"},correct:true},
{text:{en:"California",de:"Kalifornien"},correct:false},
{text:{en:"Vermont",de:"Vermont"},correct:false},
{text:{en:"Massachusetts",de:"Massachusetts"},correct:false}],
mapView:{center:[-74.4,41.7],zoom:9},
explanation:{en:"Woodstock was held in Bethel, NY — not in the town of Woodstock itself.",de:"Woodstock fand in Bethel, NY statt — nicht in der Stadt Woodstock selbst."},
relatedTour:"musicworld"},
{id:"spo_006",type:"identify",difficulty:"hard",
question:{en:"The map shows a famous filming location. Which movie franchise was filmed here?",de:"Die Karte zeigt einen berühmten Drehort. Welche Filmreihe wurde hier gedreht?"},
choices:[
{text:{en:"Lord of the Rings (New Zealand)",de:"Herr der Ringe (Neuseeland)"},correct:true},
{text:{en:"Harry Potter (Scotland)",de:"Harry Potter (Schottland)"},correct:false},
{text:{en:"Star Wars (Tunisia)",de:"Star Wars (Tunesien)"},correct:false},
{text:{en:"Indiana Jones (Jordan)",de:"Indiana Jones (Jordanien)"},correct:false}],
mapView:{center:[175.8,-38.5],zoom:7},
explanation:{en:"Peter Jackson filmed the trilogy across New Zealand's stunning landscapes.",de:"Peter Jackson drehte die Trilogie in Neuseelands atemberaubenden Landschaften."},
relatedTour:"filmlocations"},
{id:"spo_007",type:"identify",difficulty:"easy",
question:{en:"The map shows the location of a famous music festival in England. Which festival is it?",de:"Die Karte zeigt den Ort eines berühmten Musikfestivals in England. Welches Festival ist es?"},
choices:[
{text:{en:"Glastonbury Festival",de:"Glastonbury Festival"},correct:true},
{text:{en:"Reading Festival",de:"Reading Festival"},correct:false},
{text:{en:"Isle of Wight Festival",de:"Isle of Wight Festival"},correct:false},
{text:{en:"Download Festival",de:"Download Festival"},correct:false}],
mapView:{center:[-2.59,51.16],zoom:9},
explanation:{en:"Glastonbury Festival in Somerset, England, is the world's largest greenfield music festival.",de:"Das Glastonbury Festival in Somerset, England, ist das größte Freiluft-Musikfestival der Welt."},
relatedTour:"musicworld"},
{id:"spo_008",type:"identify",difficulty:"easy",
question:{en:"The map shows a famous stadium. Which is it?",de:"Die Karte zeigt ein berühmtes Stadion. Welches ist es?"},
choices:[
{text:{en:"Wembley Stadium (London)",de:"Wembley-Stadion (London)"},correct:true},
{text:{en:"Camp Nou (Barcelona)",de:"Camp Nou (Barcelona)"},correct:false},
{text:{en:"Maracanã (Rio)",de:"Maracanã (Rio)"},correct:false},
{text:{en:"Allianz Arena (Munich)",de:"Allianz Arena (München)"},correct:false}],
mapView:{center:[-0.279,51.556],zoom:11},
explanation:{en:"Wembley Stadium seats 90,000 and hosts the FA Cup Final and England internationals.",de:"Das Wembley-Stadion fasst 90.000 Zuschauer und ist Austragungsort des FA Cups und englischer Länderspiele."},
relatedTour:"worldcup"},
{id:"spo_009",type:"knowledge",difficulty:"hard",
question:{en:"Which mountain is considered the most dangerous of the 14 eight-thousanders?",de:"Welcher Berg gilt als der gefährlichste der 14 Achttausender?"},
choices:[
{text:{en:"Annapurna (32% fatality rate)",de:"Annapurna (32% Sterberate)"},correct:true},
{text:{en:"K2 (23% fatality rate)",de:"K2 (23% Sterberate)"},correct:false},
{text:{en:"Nanga Parbat (21% fatality rate)",de:"Nanga Parbat (21% Sterberate)"},correct:false},
{text:{en:"Kangchenjunga (15% fatality rate)",de:"Kangchenjunga (15% Sterberate)"},correct:false}],
mapView:{center:[83.82,28.6],zoom:10},
explanation:{en:"Annapurna has the highest fatality-to-summit ratio of any 8,000m peak.",de:"Annapurna hat die höchste Todesrate aller 8.000m-Gipfel."},
relatedTour:"summits14"},
{id:"spo_010",type:"locate",difficulty:"medium",
question:{en:"Click where the Tour de France traditionally finishes.",de:"Klicke, wo die Tour de France traditionell endet."},
target:[2.295,48.874],mapView:{center:[2,47],zoom:5},
explanation:{en:"The Tour de France finishes on the Champs-Élysées in Paris since 1975.",de:"Die Tour de France endet seit 1975 auf den Champs-Élysées in Paris."},
relatedTour:"olympics"},
{id:"spo_011",type:"identify",difficulty:"medium",
question:{en:"The map shows a city famous for its annual carnival. Which city?",de:"Die Karte zeigt eine Stadt, berühmt für ihren jährlichen Karneval. Welche Stadt?"},
choices:[
{text:{en:"Rio de Janeiro",de:"Rio de Janeiro"},correct:true},
{text:{en:"Venice",de:"Venedig"},correct:false},
{text:{en:"New Orleans",de:"New Orleans"},correct:false},
{text:{en:"Cologne",de:"Köln"},correct:false}],
mapView:{center:[-43.17,-22.91],zoom:11},
explanation:{en:"Rio Carnival attracts 2 million people daily and is the world's largest carnival.",de:"Der Karneval in Rio zieht täglich 2 Millionen Menschen an und ist der größte Karneval der Welt."},
relatedTour:"worldcup"},
{id:"spo_012",type:"identify",difficulty:"hard",
question:{en:"The map shows a rock-carved ancient city. What is this UNESCO site?",de:"Die Karte zeigt eine in Fels gehauene antike Stadt. Welches UNESCO-Welterbe ist das?"},
choices:[
{text:{en:"Petra (Jordan)",de:"Petra (Jordanien)"},correct:true},
{text:{en:"Angkor Wat (Cambodia)",de:"Angkor Wat (Kambodscha)"},correct:false},
{text:{en:"Mesa Verde (USA)",de:"Mesa Verde (USA)"},correct:false},
{text:{en:"Cappadocia (Turkey)",de:"Kappadokien (Türkei)"},correct:false}],
mapView:{center:[35.44,30.33],zoom:10},
explanation:{en:"Petra was carved into rose-red cliffs by the Nabataeans over 2,000 years ago.",de:"Petra wurde vor über 2.000 Jahren von den Nabatäern in rosenrote Felswände gemeißelt."},
relatedTour:"lostwonders"}
]
};
