// ══════════════════════════════════════════════════════════════
// GEOPULSE V2.0 — 5 New Guided Tours (Tours #36–#40)
// Loaded after main.js; merges into window._TOURS_REF
// ══════════════════════════════════════════════════════════════
(function() {
    const NEW_TOURS = {
        aurorahunters: {
            name: 'Aurora Hunters — Northern Lights',
            name_de: 'Polarlichtjäger — Nordlichter',
            category: 'science',
            steps: [
                { center: [19.01, 69.65], zoom: 10, title: '🌌 TROMSØ — AURORA CAPITAL', text: 'Tromsø, Norway (69°N) sits inside the auroral oval — the ring around the magnetic pole where aurora activity peaks. From September to March, the city experiences polar night, making it the world\'s top aurora destination. The Northern Lights occur when charged particles from solar wind collide with atmospheric gases at 100–300 km altitude, creating curtains of green (oxygen), purple and red (nitrogen) light.', layers: ['aurora'] },
                { center: [-21.93, 64.15], zoom: 8, title: '🌌 ICELAND — LAND OF FIRE & LIGHT', text: 'Iceland\'s lack of light pollution and position at 64°N makes the entire island an aurora viewing platform. The best displays occur during high Kp-index events (5+), when the auroral oval expands southward. Iceland also sits on the Mid-Atlantic Ridge — one of the few places where tectonic plates are visible above sea level.', layers: ['aurora'] },
                { center: [-147.72, 64.84], zoom: 7, title: '🌌 FAIRBANKS, ALASKA — AURORA SCIENCE', text: 'Fairbanks, Alaska is home to the Geophysical Institute at the University of Alaska, which pioneered aurora research. The city sits directly under the auroral oval at 64°N. Aurora borealis is caused by the solar wind — a stream of plasma from the Sun traveling at 400–800 km/s. When it hits Earth\'s magnetosphere, particles are funneled toward the poles along magnetic field lines.', layers: ['aurora'] },
                { center: [-114.37, 62.45], zoom: 8, title: '🌌 YELLOWKNIFE — CANADA\'S AURORA BELT', text: 'Yellowknife, Northwest Territories, Canada sits beneath the auroral oval and has flat terrain with minimal cloud cover — ideal for aurora photography. The city experiences 240+ nights of aurora activity per year. Aurora colors depend on altitude: green at 100–200 km (oxygen), red above 200 km (oxygen), blue/purple below 100 km (nitrogen).', layers: ['aurora'] },
                { center: [20.22, 67.86], zoom: 9, title: '🌌 KIRUNA — EUROPE\'S SPACE HUB', text: 'Kiruna, Sweden hosts ESRANGE — the European Space and Sounding Rocket Range, used for aurora research since 1966. The town is also home to the world\'s largest underground iron ore mine (LKAB). Kiruna sits at 67°N, well within the auroral zone. The nearby Abisko National Park is considered one of Earth\'s best aurora viewing locations due to the "blue hole of Abisko" — a microclimate creating clear skies.', layers: ['aurora'] },
                { center: [33.09, 68.97], zoom: 8, title: '🌌 MURMANSK — ARCTIC RUSSIA', text: 'Murmansk is the world\'s largest city above the Arctic Circle (population ~270,000). Despite extreme cold (-30°C winters), it remains ice-free due to the North Atlantic Current. The Kola Peninsula has been used for Soviet/Russian aurora and ionosphere research for decades. During strong geomagnetic storms (Kp 7+), aurora can be visible as far south as central Europe.', layers: ['aurora'] },
                { center: [168.66, -44.99], zoom: 8, title: '🌌 QUEENSTOWN, NZ — AURORA AUSTRALIS', text: 'The Southern Hemisphere has its own aurora — Aurora Australis. Queenstown and Stewart Island in New Zealand\'s South Island (46°S) occasionally see spectacular southern lights, especially during high Kp events. Aurora Australis is less commonly photographed because most land at equivalent southern latitudes is ocean. Antarctica offers the best views.', layers: ['aurora'] },
                { center: [-68.30, -54.80], zoom: 8, title: '🌌 USHUAIA — SOUTHERNMOST AURORA', text: 'Ushuaia, Argentina (54°S) — the world\'s southernmost city — occasionally witnesses Aurora Australis during strong geomagnetic storms. The aurora oval is a mirror of the northern one, centered on the geomagnetic south pole in Antarctica. The NOAA OVATION model (shown on this map) predicts aurora probability in real-time using solar wind data from the DSCOVR satellite at Lagrange Point 1, 1.5 million km from Earth.', layers: ['aurora'] }
            ]
        },
        cosmicimpacts: {
            name: 'Cosmic Impacts — Asteroids That Shaped Earth',
            name_de: 'Kosmische Einschläge — Asteroiden die die Erde formten',
            category: 'science',
            steps: [
                { center: [-89.52, 21.36], zoom: 8, title: '☄️ CHICXULUB — THE DINOSAUR KILLER', text: '66 million years ago, a 10–15 km asteroid struck the Yucatán Peninsula at ~20 km/s. The impact released 10 billion Hiroshima bombs of energy, creating a 180 km crater now buried under limestone. The resulting "impact winter" — years of darkness from ejected debris — wiped out 76% of all species, including non-avian dinosaurs. The crater was only discovered in 1978 by geophysicists searching for oil.', layers: ['fireballs'] },
                { center: [101.90, 60.90], zoom: 6, title: '☄️ TUNGUSKA — THE MYSTERY BLAST (1908)', text: 'On June 30, 1908, a massive explosion flattened 2,150 km² of Siberian forest — 80 million trees — near the Podkamennaya Tunguska River. The blast was ~15 megatons (1,000× Hiroshima) but left no crater. Scientists believe a 50–80 meter asteroid or comet fragment exploded 5–10 km above the surface (an "airburst"). The remote location meant no human casualties, but the shock wave was detected worldwide. It remains the largest impact event in recorded history.', layers: ['fireballs'] },
                { center: [61.37, 54.82], zoom: 8, title: '☄️ CHELYABINSK — CAUGHT ON CAMERA (2013)', text: 'On February 15, 2013, a 20-meter asteroid entered Earth\'s atmosphere at 66,000 km/h and exploded over Chelyabinsk, Russia with the force of 500 kilotons (30× Hiroshima). The shockwave damaged 7,200 buildings and injured 1,500 people — mostly from broken glass. It was the first major impact event captured by hundreds of dashcams and smartphones, making it the most documented meteor strike in history. NASA\'s CNEOS fireball database (shown on this map) tracks such events globally.', layers: ['fireballs'] },
                { center: [-111.02, 35.03], zoom: 12, title: '☄️ BARRINGER CRATER — BEST PRESERVED', text: 'Barringer Crater (Meteor Crater) in Arizona is the best-preserved impact crater on Earth. A 50-meter nickel-iron asteroid struck 50,000 years ago at ~45,000 km/h, creating a 1.2 km wide, 170 m deep crater. The impact energy was ~10 megatons. NASA used this site to train Apollo astronauts for the Moon. The crater is privately owned and serves as a research site for planetary science.', layers: ['fireballs'] },
                { center: [27.00, -27.00], zoom: 7, title: '☄️ VREDEFORT — EARTH\'S LARGEST CRATER', text: 'The Vredefort structure in South Africa is the largest verified impact crater on Earth — originally ~300 km in diameter, formed 2.02 billion years ago by an asteroid estimated at 10–15 km across. The impact was so powerful it created a multi-ring basin now deeply eroded. The central uplift is visible as the Vredefort Dome, a UNESCO World Heritage Site. This impact may have disrupted early life on Earth and reshaped the Witwatersrand Basin — now the world\'s largest gold deposit.', layers: [] },
                { center: [-81.18, 46.60], zoom: 7, title: '☄️ SUDBURY — IMPACT & MINING', text: 'The Sudbury Basin in Ontario, Canada was created 1.85 billion years ago by a 10–15 km asteroid. The 250 km structure is now one of the world\'s richest mining districts — the impact melted rocks containing nickel, copper, and platinum-group metals. Sudbury produces 10% of the world\'s nickel supply. The basin also contains "shatter cones" — cone-shaped fractures unique to hypervelocity impacts, proving the extraterrestrial origin.', layers: [] },
                { center: [10.58, 48.85], zoom: 11, title: '☄️ NÖRDLINGER RIES — GERMAN IMPACT TOWN', text: 'The town of Nördlingen, Bavaria sits inside a 24 km impact crater created 14.8 million years ago. The medieval town walls are built from suevite — rock created by the impact\'s extreme heat and pressure. The crater was long thought to be volcanic until 1960, when Dr. Eugene Shoemaker proved its impact origin by finding coesite (a high-pressure quartz mineral). St. George\'s Church contains 72,000 tons of suevite with microscopic diamonds formed by the impact shock.', layers: [] },
                { center: [-68.70, 51.38], zoom: 7, title: '☄️ MANICOUAGAN — THE EYE OF QUÉBEC', text: 'The Manicouagan reservoir in Québec, Canada fills a 100 km ring-shaped impact crater formed 214 million years ago. Visible from space as the "Eye of Québec," it is one of the oldest and largest well-preserved craters on Earth. The impact may coincide with the end-Triassic extinction event. The reservoir now serves as a massive hydroelectric facility (Manic-5), producing ~2,600 MW — demonstrating how cosmic violence was repurposed into clean energy.', layers: [] }
            ]
        },
        climatecrisis: {
            name: 'Climate Crisis — Evidence From Space',
            name_de: 'Klimakrise — Beweise aus dem All',
            category: 'science',
            steps: [
                { center: [147.70, -18.30], zoom: 6, title: '🌡️ GREAT BARRIER REEF — BLEACHING', text: 'The Great Barrier Reef (2,300 km, visible from space) has experienced 7 mass bleaching events since 1998 — with 2024 being the worst on record. When ocean temperatures rise 1–2°C above normal for 4+ weeks, corals expel their symbiotic algae and turn white. If stress persists, they die. NASA\'s sea surface temperature data (toggle SST layer) shows the warming trend. The reef supports 1,500 fish species and generates $6.4B annually for Australia\'s economy.', layers: ['sst'] },
                { center: [15.63, 78.22], zoom: 7, title: '🧊 SVALBARD — ARCTIC AMPLIFICATION', text: 'Svalbard, Norway (78°N) is warming 3–5× faster than the global average — a phenomenon called "Arctic amplification." Since 1970, average temperatures have risen by 4°C. Glaciers that took millennia to form are retreating at 50–100 meters per year. The Svalbard Global Seed Vault, built to protect humanity\'s crop diversity, was flooded in 2017 when permafrost melted around its entrance — infrastructure designed for eternal ice is failing as the Arctic transforms.', layers: ['temperature'] },
                { center: [-62.21, -3.47], zoom: 5, title: '🌳 AMAZON — THE LUNGS UNDER THREAT', text: 'The Amazon rainforest produces 6% of Earth\'s oxygen and stores 150–200 billion tons of carbon. But deforestation and drought are pushing it toward a "tipping point" — the moment the forest can no longer sustain itself and begins converting to savanna. NASA FIRMS fire data (toggle Wildfires) shows the scale of burning. Since 1970, ~17% of the Amazon has been destroyed. Scientists estimate the tipping point lies at 20–25% deforestation — we are dangerously close.', layers: ['fires'] },
                { center: [59.60, 45.00], zoom: 7, title: '🏜️ ARAL SEA — THE VANISHED LAKE', text: 'The Aral Sea was once the world\'s 4th largest lake (68,000 km²). Soviet-era irrigation projects diverted its feeder rivers for cotton farming. By 2014, the eastern basin had completely dried up. Fishing villages now sit 100+ km from water. The exposed seabed creates toxic dust storms carrying pesticides across Central Asia. NASA satellite imagery documents this as one of the worst human-caused environmental disasters in history.', layers: [] },
                { center: [7.66, 45.98], zoom: 9, title: '🏔️ ALPINE GLACIERS — DISAPPEARING ICE', text: 'The European Alps have lost over 60% of their glacier volume since 1850. Switzerland\'s glaciers alone shrank by 6.2% in the single year 2022–2023 — the worst loss ever recorded. The Aletsch Glacier, Europe\'s largest, has retreated 3.5 km. Glacier loss threatens freshwater supply for 100+ million Europeans, hydroelectric power generation, and winter tourism. At current rates, the Alps could be ice-free by 2100.', layers: ['temperature'] },
                { center: [179.19, -8.52], zoom: 10, title: '🌊 TUVALU — DROWNING NATION', text: 'Tuvalu (population 11,000) is one of the first nations facing extinction from sea-level rise. The highest point on most atolls is just 4.6 meters above sea level. With seas rising 3.3 mm/year (accelerating), Tuvalu could become uninhabitable by 2050–2100. In 2023, Tuvalu signed a treaty with Australia to accept climate refugees. The nation is preserving its sovereignty digitally — creating a virtual version of itself as territorial waters disappear.', layers: ['sst'] },
                { center: [-41.0, 72.0], zoom: 4, title: '🧊 GREENLAND — ICE SHEET COLLAPSE', text: 'Greenland\'s ice sheet contains enough water to raise global sea levels by 7.2 meters. It is losing ~270 billion tons of ice per year — a rate that has tripled since the 1990s. Meltwater lubricates the base of glaciers, accelerating their flow to the ocean. Jakobshavn Glacier alone calves enough ice daily to supply New York City\'s water for a year. Complete melting would redraw the coastlines of every continent.', layers: ['temperature'] },
                { center: [0, -75], zoom: 3, title: '🌍 ANTARCTICA — THE DOOMSDAY GLACIER', text: 'The Thwaites Glacier in West Antarctica (nicknamed the "Doomsday Glacier") is 120 km wide and holds enough ice to raise seas by 65 cm alone. Its grounding line is retreating, and warm ocean water is melting it from below. If Thwaites collapses, it could destabilize the entire West Antarctic Ice Sheet — raising seas by 3.3 meters and displacing hundreds of millions of people worldwide. Scientists are racing to understand its timeline.', layers: ['sst', 'temperature'] }
            ]
        },
        greatmigrations: {
            name: 'Great Migrations — Epic Animal Journeys',
            name_de: 'Große Wanderungen — Epische Tierreisen',
            category: 'science',
            steps: [
                { center: [-3.44, 55.38], zoom: 4, title: '🕊️ ARCTIC TERN — POLE TO POLE', text: 'The Arctic Tern makes the longest migration of any animal — 71,000 km annually, pole to pole and back. Breeding in the Arctic (Iceland, Scandinavia, Canada) and wintering in Antarctica, these 100-gram birds experience more daylight than any other creature on Earth. Over a 30-year lifespan, a single tern flies the equivalent of 3 round trips to the Moon. They navigate using Earth\'s magnetic field, the Sun, and star patterns.', layers: [] },
                { center: [-36.0, -54.0], zoom: 5, title: '🐋 HUMPBACK WHALE — OCEAN MARATHON', text: 'Humpback whales migrate up to 16,000 km per year — one of the longest migrations of any mammal. They feed in polar waters (Antarctica, Alaska) during summer, then travel to tropical breeding grounds (Hawaii, Caribbean, Tonga) in winter. They can travel 1,000+ km without eating, living off stored blubber. Their songs — complex vocalizations lasting up to 20 minutes — can travel 30,000 km through ocean sound channels.', layers: [] },
                { center: [-100.33, 40.0], zoom: 5, title: '🦋 MONARCH BUTTERFLY — 4 GENERATIONS', text: 'Monarch butterflies migrate 4,800 km from Canada/USA to central Mexico each autumn — but no single butterfly makes the round trip. It takes 4 generations: the "super generation" born in autumn flies south to winter in oyamel fir forests near Mexico City, then begins the return north in spring. Their descendants continue northward over 3 more generations. How they navigate to a place they\'ve never been remains one of biology\'s great mysteries — likely using a sun compass and magnetic sense.', layers: [] },
                { center: [34.80, -2.50], zoom: 7, title: '🦬 WILDEBEEST — SERENGETI CIRCUIT', text: 'The Great Migration in East Africa involves ~1.5 million wildebeest, 400,000 zebras, and 200,000 gazelles circling 800 km between Tanzania\'s Serengeti and Kenya\'s Masai Mara. This annual clockwise migration follows rainfall and fresh grass. The Mara River crossings are among nature\'s most dramatic spectacles — thousands of animals plunge into crocodile-infested waters. This migration has continued for over a million years.', layers: [] },
                { center: [-152.49, 66.56], zoom: 5, title: '🦌 CARIBOU — ARCTIC HERDS', text: 'The Porcupine caribou herd migrates 2,400 km annually between winter ranges in Alaska\'s interior and calving grounds on the Arctic coastal plain — one of the longest land migrations on Earth. Up to 200,000 caribou travel together, crossing frozen rivers and mountain passes. Their hooves change with the seasons: soft pads in summer for tundra, hard edges in winter for ice. Climate change is disrupting their timing — insects emerge before calving, reducing calf survival.', layers: [] },
                { center: [-55.0, 15.0], zoom: 4, title: '🐢 LEATHERBACK TURTLE — DEEP DIVER', text: 'Leatherback sea turtles migrate up to 16,000 km across entire ocean basins — from nesting beaches in the tropics to feeding grounds in sub-Arctic waters. They can dive to 1,280 meters (deeper than any other turtle) and cross the Atlantic in 150 days. Females return to the exact beach where they hatched to lay eggs, navigating by Earth\'s magnetic field. Populations have declined 95% since 1980 due to fishing bycatch and plastic pollution.', layers: [] },
                { center: [12.0, 45.0], zoom: 4, title: '🦩 WHITE STORK — EUROPE TO AFRICA', text: 'European White Storks migrate 20,000 km annually between breeding grounds in Europe and wintering areas in sub-Saharan Africa. They avoid crossing the Mediterranean Sea (no thermal updrafts over water), instead funneling through the Strait of Gibraltar or the Bosphorus. Some storks now winter in Spain and Portugal, feeding on landfill sites — an example of how human waste is altering ancient migration patterns.', layers: [] },
                { center: [174.0, -41.0], zoom: 4, title: '🐦 BAR-TAILED GODWIT — NONSTOP RECORD', text: 'In 2022, a Bar-tailed Godwit (B6) flew 13,560 km nonstop from Alaska to Tasmania — the longest recorded nonstop flight of any bird. These 300-gram shorebirds fly for 11 days without eating, drinking, or sleeping, crossing the entire Pacific Ocean. Before departure, they nearly double their body weight with fat reserves while their digestive organs shrink to save weight. They navigate using the Sun, stars, and Earth\'s magnetic field, with no landmarks over open ocean.', layers: [] }
            ]
        },
        spycraft: {
            name: 'Espionage World — Famous Spy Sites',
            name_de: 'Spionage-Welt — Berühmte Geheimdienstorte',
            category: 'geopolitics',
            steps: [
                { center: [-77.15, 38.95], zoom: 12, title: '🕵️ CIA HEADQUARTERS — LANGLEY', text: 'The George Bush Center for Intelligence in Langley, Virginia is the headquarters of the Central Intelligence Agency (CIA). Founded in 1947, the CIA conducts foreign intelligence gathering and covert operations. The campus includes the famous "Kryptos" sculpture — an encrypted artwork that remains partially unsolved since 1990. The CIA employs ~21,000 people. Its budget is classified but estimated at $15+ billion annually.', layers: [] },
                { center: [-0.11, 51.49], zoom: 13, title: '🕵️ MI6 — VAUXHALL CROSS, LONDON', text: 'The SIS Building at 85 Albert Embankment houses MI6 — the UK\'s Secret Intelligence Service. Built in 1994 on the Thames, the postmodern fortress is one of the most recognizable spy buildings in the world, featured in multiple James Bond films. MI6 was officially acknowledged to exist only in 1994 — despite operating since 1909. Its current head is known internally as "C" (not "M" as in the films).', layers: [] },
                { center: [37.52, 55.58], zoom: 11, title: '🕵️ SVR/FSB — LUBYANKA & YASENEVO', text: 'Moscow houses Russia\'s two main intelligence agencies: the FSB (domestic security, headquartered in the infamous Lubyanka Building — formerly the KGB) and the SVR (foreign intelligence, at Yasenevo in Moscow\'s outskirts). The Lubyanka was a KGB prison where thousands were interrogated and executed during Stalin\'s purges. Russia\'s intelligence apparatus employs an estimated 200,000+ personnel across all agencies.', layers: [] },
                { center: [52.44, 42.57], zoom: 4, title: '🕵️ BAIKONUR — SPACE ESPIONAGE', text: 'The Baikonur Cosmodrome in Kazakhstan was the USSR\'s most closely guarded secret — the launch site for Sputnik (1957) and Yuri Gagarin (1961). CIA U-2 spy planes photographed the facility from 20 km altitude. When Gary Powers was shot down over the USSR in 1960, it triggered an international crisis. Space became the ultimate espionage battlefield — both superpowers used spy satellites to monitor each other\'s nuclear arsenals.', layers: [] },
                { center: [13.39, 52.51], zoom: 12, title: '🕵️ BERLIN — COLD WAR SPY CAPITAL', text: 'Divided Berlin was the world\'s spy capital from 1945–1989. The Berlin Wall created a physical intelligence frontier. The CIA\'s Berlin Operations Base and the KGB\'s Karlshorst headquarters were just kilometers apart. The famous Glienicke Bridge ("Bridge of Spies") was used for prisoner exchanges, including U-2 pilot Gary Powers in 1962. The Stasi (East German secret police) employed 91,000 full-time agents and 189,000 informants — surveillance on an industrial scale.', layers: [] },
                { center: [-73.97, 40.75], zoom: 11, title: '🕵️ UNITED NATIONS — DIPLOMATIC ESPIONAGE', text: 'The UN headquarters in New York is one of the world\'s most surveilled buildings. Every major power\'s diplomatic mission doubles as an intelligence station. In 2013, Edward Snowden revealed that the NSA had bugged the EU\'s UN mission, tapped Secretary-General Ban Ki-moon\'s office, and monitored 35+ world leaders\' phones. The UN complex hosts ~4,000 diplomats — many carrying diplomatic immunity that shields intelligence activities from prosecution.', layers: [] },
                { center: [116.39, 39.91], zoom: 10, title: '🕵️ MSS — CHINA\'S INTELLIGENCE MACHINE', text: 'China\'s Ministry of State Security (MSS) is among the world\'s largest intelligence agencies. Unlike Western agencies focused on HUMINT (human spies), the MSS pioneered mass cyber-espionage — hacking government systems, defense contractors, and tech companies worldwide. The 2015 OPM hack alone stole 22 million US federal employee records. China\'s "Thousand Talents Program" recruited foreign scientists, blurring the line between academic exchange and espionage.', layers: [] },
                { center: [-76.77, 39.11], zoom: 10, title: '🕵️ NSA — FORT MEADE', text: 'The National Security Agency (NSA) at Fort Meade, Maryland is the world\'s largest signals intelligence (SIGINT) organization. Revealed in detail by Edward Snowden in 2013, the NSA operates global surveillance programs including PRISM (tech company data access), XKeyscore (internet search tool), and Tempora (fiber-optic cable tapping with UK\'s GCHQ). The NSA campus has its own power plant, shopping center, and employs 30,000–40,000 people. It intercepts an estimated 1.7 billion communications per day.', layers: [] }
            ]
        }
    };

    // Merge into main TOURS object when ready
    function mergeNewTours() {
        if (window._TOURS_REF) {
            Object.assign(window._TOURS_REF, NEW_TOURS);
            console.log('[tours_new] Merged 5 new tours into TOURS');
        } else {
            setTimeout(mergeNewTours, 500);
        }
    }
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', () => setTimeout(mergeNewTours, 1000));
    } else {
        setTimeout(mergeNewTours, 1000);
    }
})();
