// ══════════════════════════════════════════════════════════════
// GEOPULSE V2.41 — "Winds of the World" Guided Tour (#41)
// Loaded after main.js; merges into window._TOURS_REF
// ══════════════════════════════════════════════════════════════
(function() {
    const WIND_TOURS = {
        windsworld: {
            name: 'Winds of the World — Earth\'s Invisible Engine',
            name_de: 'Winde der Welt — Die unsichtbare Kraft der Erde',
            category: 'science',
            steps: [
                {
                    center: [-30.0, 52.0], zoom: 3,
                    title: '🌬️ THE JET STREAM — RIVER IN THE SKY',
                    title_de: '🌬️ DER JETSTREAM — FLUSS AM HIMMEL',
                    text: '📍 North Atlantic — Polar Jet Stream corridor\n🌪️ SPEED: 150–400 km/h at 9–12 km altitude\n\n📖 The jet stream is a narrow band of fast-moving air that snakes around the globe at the boundary between cold polar air and warm tropical air. Discovered by Japanese meteorologist Wasaburo Ooishi in the 1920s and exploited by WWII bombers, this atmospheric river is 100–200 km wide but only 1–2 km thick.\n\n🌍 WHY IT MATTERS: The polar jet stream controls European and North American weather. Its meanders (Rossby waves) determine whether London gets sun or storms. A flight from New York to London takes ~1 hour less than the return — saved by riding the jet stream at 900 km/h ground speed.\n\n⚠️ CLIMATE CHANGE: As the Arctic warms 3–4× faster than the equator, the temperature gradient weakens, causing the jet stream to slow and wobble. This leads to "stuck" weather patterns — prolonged heatwaves, floods, and polar vortex events.',
                    text_de: '📍 Nordatlantik — Polarjet-Korridor\n🌪️ GESCHWINDIGKEIT: 150–400 km/h in 9–12 km Höhe\n\n📖 Der Jetstream ist ein schmales Band schnell strömender Luft an der Grenze zwischen kalter Polarluft und warmer Tropikluft. In den 1920ern vom japanischen Meteorologen Wasaburo Ooishi entdeckt, ist dieser atmosphärische Fluss 100–200 km breit, aber nur 1–2 km dick.\n\n🌍 WARUM ES WICHTIG IST: Der Polarjet steuert das europäische Wetter. Ein Flug von New York nach London dauert ~1 Stunde weniger als der Rückflug — dank des Jetstreams.\n\n⚠️ KLIMAWANDEL: Die Arktis erwärmt sich 3–4× schneller als der Äquator. Der Temperaturunterschied wird kleiner, der Jetstream langsamer und instabiler — das führt zu „festsitzenden" Wetterlagen: Hitzewellen, Fluten und Polarwirbel-Einbrüche.',
                    layers: ['wind'], image: { wiki: 'Jet_stream', caption: 'Polar jet stream visualization' }
                },
                {
                    center: [-160.0, 32.0], zoom: 3,
                    title: '🌊 PACIFIC JET — THE STORM HIGHWAY',
                    title_de: '🌊 PAZIFISCHER JET — DIE STURMAUTOBAHN',
                    text: '📍 North Pacific Ocean — Subtropical Jet Stream\n🌪️ SPEED: 200–450 km/h (strongest on Earth)\n\n📖 The Pacific jet stream is the most powerful wind system on the planet. It forms where the massive temperature contrast between Siberia\'s icy interior and the warm Pacific Ocean creates an atmospheric pressure cannon. This jet drives storms across the Pacific and slams them into the west coast of North America.\n\n🌧️ ATMOSPHERIC RIVERS: When the Pacific jet dips south, it channels tropical moisture into narrow corridors called "atmospheric rivers" — rivers of water vapor 400 km wide carrying more water than the Mississippi. When they hit the California coast, they can dump 6 months of rain in 3 days.\n\n✈️ AVIATION: Transpacific flights from Tokyo to Los Angeles ride this jet, shaving 2+ hours off the journey. In January 2024, a British Airways flight hit a 1,300 km/h ground speed over the Pacific — the jet stream added 400 km/h to its airspeed.',
                    text_de: '📍 Nordpazifik — Subtropischer Jetstream\n🌪️ GESCHWINDIGKEIT: 200–450 km/h (der stärkste der Erde)\n\n📖 Der pazifische Jetstream ist das mächtigste Windsystem des Planeten. Er entsteht durch den extremen Temperaturkontrast zwischen Sibiriens Eismassen und dem warmen Pazifik. Dieser Jet treibt Stürme über den Pazifik und schleudert sie gegen die Westküste Nordamerikas.\n\n🌧️ ATMOSPHÄRISCHE FLÜSSE: Wenn der Pazifik-Jet nach Süden abknickt, kanalisiert er tropische Feuchtigkeit in „atmosphärische Flüsse" — 400 km breite Wasserdampf-Ströme, die mehr Wasser transportieren als der Mississippi.\n\n✈️ LUFTFAHRT: Flüge von Tokio nach Los Angeles nutzen diesen Jet und sparen 2+ Stunden. 2024 erreichte ein British-Airways-Flug 1.300 km/h Bodengeschwindigkeit — der Jetstream lieferte 400 km/h zusätzlich.',
                    layers: ['wind']
                },
                {
                    center: [-40.0, 15.0], zoom: 3,
                    title: '🏜️ TRADE WINDS — THE ENGINE OF EXPLORATION',
                    title_de: '🏜️ PASSATWINDE — DER MOTOR DER ENTDECKUNGEN',
                    text: '📍 Tropical Atlantic — Northeast Trade Wind belt (10°–30°N)\n💨 SPEED: 20–40 km/h (remarkably steady)\n\n📖 The trade winds are the most consistent winds on Earth — so reliable that European sailors named them for their importance to trade. Blowing from the northeast in the Northern Hemisphere and southeast in the Southern, they powered the Age of Sail for 400 years. Columbus crossed the Atlantic in 1492 by sailing south to catch the trades, then riding them west to the Caribbean.\n\n🏜️ SAHARAN DUST: These winds carry 180 million tons of Saharan dust across the Atlantic every year. This dust fertilizes the Amazon rainforest with phosphorus — without Africa\'s wind-blown minerals, the world\'s largest rainforest would be nutrient-starved.\n\n🌀 HURRICANE FUEL: Trade winds push warm surface water westward, piling it up in the Caribbean at 28°C+. This warm water pool is the fuel tank for Atlantic hurricanes. When trade winds weaken during El Niño years, fewer hurricanes form.',
                    text_de: '📍 Tropischer Atlantik — Nordost-Passatwind-Gürtel (10°–30°N)\n💨 GESCHWINDIGKEIT: 20–40 km/h (bemerkenswert gleichmäßig)\n\n📖 Die Passatwinde sind die beständigsten Winde der Erde — so zuverlässig, dass europäische Seeleute sie nach ihrer Bedeutung für den Handel benannten. Kolumbus überquerte 1492 den Atlantik, indem er nach Süden segelte, um die Passate zu erreichen.\n\n🏜️ SAHARASTAUB: Diese Winde tragen jährlich 180 Millionen Tonnen Saharastaub über den Atlantik. Dieser Staub düngt den Amazonas-Regenwald mit Phosphor — ohne Afrikas windgetragene Mineralien wäre der größte Regenwald der Welt nährstoffarm.\n\n🌀 HURRIKAN-TREIBSTOFF: Passatwinde schieben warmes Oberflächenwasser nach Westen. Dieses warme Wasser ist der Kraftstofftank für atlantische Hurrikane.',
                    layers: ['wind'], image: { wiki: 'Trade_wind', caption: 'Global trade wind patterns' }
                },
                {
                    center: [75.0, 18.0], zoom: 4,
                    title: '🌧️ THE MONSOON — BREATH OF A CONTINENT',
                    title_de: '🌧️ DER MONSUN — DER ATEM EINES KONTINENTS',
                    text: '📍 Indian Ocean → South Asia\n💨 REVERSAL: 180° wind shift between summer and winter\n\n📖 The Asian monsoon is the most powerful seasonal wind shift on Earth. In summer, the Indian subcontinent heats up faster than the ocean, creating a massive low-pressure zone that sucks in moisture-laden air from the Indian Ocean. The wind reverses completely — from dry northeast winter winds to wet southwest summer winds.\n\n🌾 FEEDING 2 BILLION: Monsoon rains deliver 70–90% of India\'s annual rainfall in just 4 months (June–September). Agriculture for 2 billion people depends on these winds arriving on time. A late or weak monsoon means famine; an early or excessive one means catastrophic flooding.\n\n📊 SCALE: At peak intensity, the monsoon moves more water than any other weather system — the equivalent of 40 Amazon Rivers. Mumbai receives 2,200 mm of rain during monsoon season. The Meghalaya plateau in northeast India holds the world record: 11,871 mm in one year.\n\n⚠️ CLIMATE SHIFT: Models predict monsoons becoming more erratic — fewer rainy days but more intense downpours. The "pulsing" monsoon may replace the steady monsoon.',
                    text_de: '📍 Indischer Ozean → Südasien\n💨 UMKEHR: 180° Windrichtungswechsel zwischen Sommer und Winter\n\n📖 Der asiatische Monsun ist die mächtigste saisonale Windverschiebung der Erde. Im Sommer erhitzt sich der indische Subkontinent schneller als der Ozean und erzeugt ein Tiefdruckgebiet, das feuchte Luft vom Indischen Ozean ansaugt.\n\n🌾 ERNÄHRUNG VON 2 MILLIARDEN: Monsunregen liefert 70–90% von Indiens Jahresniederschlag in nur 4 Monaten. Die Landwirtschaft für 2 Milliarden Menschen hängt davon ab.\n\n📊 AUSMAẞ: Auf dem Höhepunkt bewegt der Monsun mehr Wasser als jedes andere Wettersystem — das Äquivalent von 40 Amazonas-Flüssen. Mumbai erhält 2.200 mm Regen während der Monsunzeit.',
                    layers: ['wind', 'weather']
                },
                {
                    center: [100.0, -45.0], zoom: 3,
                    title: '🌊 ROARING FORTIES — ENDLESS WIND',
                    title_de: '🌊 BRÜLLENDE VIERZIGER — ENDLOSER WIND',
                    text: '📍 Southern Ocean — 40°–50°S latitude\n💨 SPEED: 50–100+ km/h sustained, waves 10–15m\n\n📖 The Roaring Forties are the most powerful sustained surface winds on Earth. At these latitudes, there is virtually no land to slow the wind — it circles the entire globe uninterrupted. Below 50°S, conditions intensify into the "Furious Fifties" and "Screaming Sixties."\n\n⚓ MARITIME HISTORY: Clipper ships in the 19th century rode the Roaring Forties on the "Clipper Route" from Europe to Australia, reaching speeds impossible in calmer waters. The route shaved weeks off the journey but was terrifyingly dangerous — icebergs, 15-meter waves, and the nearest rescue thousands of kilometers away.\n\n🌊 SOUTHERN OCEAN PUMP: These winds drive the Antarctic Circumpolar Current — the world\'s most powerful ocean current, moving 100–150 million cubic meters per second (600× the Amazon River). This current isolates Antarctica and drives global ocean circulation, distributing heat and nutrients worldwide.\n\n🏆 GOLDEN GLOBE RACE: Solo sailors in the Vendée Globe race must cross the Roaring Forties twice. Average wave height: 6m. Some swells reach 30m — taller than a 10-story building.',
                    text_de: '📍 Südlicher Ozean — 40°–50° südliche Breite\n💨 GESCHWINDIGKEIT: 50–100+ km/h Dauerwind, Wellen 10–15m\n\n📖 Die Brüllenden Vierziger sind die stärksten anhaltenden Oberflächenwinde der Erde. Auf diesen Breitengraden gibt es praktisch kein Land — der Wind umkreist den gesamten Globus ohne Unterbrechung.\n\n⚓ MARITIME GESCHICHTE: Klipper im 19. Jahrhundert nutzten die Brüllenden Vierziger auf der „Klipper-Route" von Europa nach Australien.\n\n🌊 SÜDOZEAN-PUMPE: Diese Winde treiben den Antarktischen Zirkumpolarstrom — die mächtigste Meeresströmung der Welt, die 100–150 Millionen Kubikmeter pro Sekunde bewegt (600× der Amazonas).',
                    layers: ['wind', 'sst']
                },
                {
                    center: [-97.0, 35.5], zoom: 5,
                    title: '🌪️ TORNADO ALLEY — WHERE WINDS COLLIDE',
                    title_de: '🌪️ TORNADO ALLEY — WO WINDE KOLLIDIEREN',
                    text: '📍 Central USA — Texas to South Dakota\n🌪️ 1,200+ tornadoes per year in the US alone\n\n📖 Tornado Alley is where three air masses collide: cold dry air from Canada, warm moist air from the Gulf of Mexico, and dry air from the Rocky Mountains. When the jet stream dips into this region, it creates violent supercell thunderstorms that spawn tornadoes.\n\n💨 PHYSICS: A tornado forms when wind shear (changing speed/direction with altitude) creates a horizontal rotating tube of air. The supercell\'s updraft tilts this tube vertical, creating a mesocyclone. When the rotating column reaches the ground — it becomes a tornado.\n\n📊 POWER SCALE (EF0–EF5):\n• EF0: 105–137 km/h — branches broken\n• EF3: 218–266 km/h — roofs torn off, trains derailed\n• EF5: 322+ km/h — houses leveled, cars thrown 100m+\n\n🏚️ DEADLIEST: The 2011 Joplin, Missouri EF5 killed 158 people. The 1925 Tri-State Tornado traveled 352 km — the longest path ever — killing 695 people across 3 states in 3.5 hours.\n\n🔬 FACT: The US gets 75% of all tornadoes worldwide. No other country has this specific triple-collision geography.',
                    text_de: '📍 Zentral-USA — Texas bis South Dakota\n🌪️ 1.200+ Tornados pro Jahr allein in den USA\n\n📖 Tornado Alley ist der Ort, an dem drei Luftmassen kollidieren: kalte trockene Luft aus Kanada, warme feuchte Luft aus dem Golf von Mexiko und trockene Luft von den Rocky Mountains. Wenn der Jetstream in diese Region eintaucht, entstehen heftige Superzellen-Gewitter.\n\n📊 STÄRKESKALA (EF0–EF5):\n• EF0: 105–137 km/h — Äste brechen\n• EF3: 218–266 km/h — Dächer abgerissen\n• EF5: 322+ km/h — Häuser dem Erdboden gleichgemacht\n\n🔬 FAKT: Die USA haben 75% aller Tornados weltweit.',
                    layers: ['wind', 'weather'], image: { wiki: 'Tornado', caption: 'Supercell thunderstorm spawning a tornado' }
                },
                {
                    center: [167.0, -77.0], zoom: 4,
                    title: '❄️ KATABATIC WINDS — THE ICE DRAGONS',
                    title_de: '❄️ KATABATISCHE WINDE — DIE EISDRACHEN',
                    text: '📍 Antarctica — ice sheet drainage basins\n💨 SPEED: Up to 300 km/h (hurricane force+)\n\n📖 Katabatic winds are gravity-driven: cold, dense air forms over the Antarctic ice sheet (average elevation 2,500m) and pours downhill toward the coast like an invisible avalanche. The Coriolis effect deflects them left (Southern Hemisphere), creating persistent easterly gales along the Antarctic coastline.\n\n🥶 CAPE DENISON: This point in Commonwealth Bay, Antarctica is the windiest place on Earth at sea level. Average wind speed: 80 km/h. Gusts regularly exceed 240 km/h. Douglas Mawson\'s 1912 expedition was trapped here for a year, calling it "the home of the blizzard."\n\n🏔️ HOW THEY FORM: The ice sheet radiates heat into space, cooling the air directly above it. This cold, dense air is heavier than the warmer air below. Gravity pulls it downhill, accelerating through valleys and ice channels. By the time it reaches the coast, it can be moving at hurricane speed.\n\n🌡️ TEMPERATURE DROP: Katabatic winds can drop temperatures 20°C in minutes. At McMurdo Station, researchers must rope themselves to buildings during katabatic events.',
                    text_de: '📍 Antarktis — Eisschildabflussbecken\n💨 GESCHWINDIGKEIT: Bis zu 300 km/h (Hurrikanstärke+)\n\n📖 Katabatische Winde sind schwerkraftgetrieben: Kalte, dichte Luft bildet sich über dem antarktischen Eisschild (durchschnittliche Höhe 2.500m) und stürzt wie eine unsichtbare Lawine zur Küste hinab.\n\n🥶 KAP DENISON: Dieser Punkt in der Commonwealth Bay ist der windigste Ort der Erde auf Meereshöhe. Durchschnittliche Windgeschwindigkeit: 80 km/h. Böen übersteigen regelmäßig 240 km/h.\n\n🌡️ TEMPERATURABFALL: Katabatische Winde können die Temperatur in Minuten um 20°C senken.',
                    layers: ['wind', 'temperature']
                },
                {
                    center: [-5.5, 36.0], zoom: 6,
                    title: '🌬️ THE VENTURI EFFECT — FUNNELED FURY',
                    title_de: '🌬️ DER VENTURI-EFFEKT — KANALISIERTE WUCHT',
                    text: '📍 Strait of Gibraltar — where Atlantic meets Mediterranean\n💨 FAMOUS WINDS: Levante (east), Poniente (west), Mistral, Bora\n\n📖 When wind is forced through a narrow gap between mountains or coastlines, it accelerates — the Venturi effect. The Strait of Gibraltar (14 km wide) acts as a natural wind tunnel between Africa and Europe. The Levante wind can blow for days, creating chaotic seas and grounding ferries.\n\n🌊 MISTRAL (France): Cold air from the Massif Central is funneled down the Rhône Valley, accelerating to 100+ km/h as it exits into the Gulf of Lion. This bone-dry, brutally cold wind can blow for days. It\'s so notorious that French law recognizes it as grounds for temporary insanity.\n\n❄️ BORA (Adriatic): Arctic air from the Dinaric Alps plunges 1,000m to the Adriatic coast in minutes. In Trieste, Italy, chains are installed on sidewalks for pedestrians to hold onto during Bora events. Wind speeds: 150–200 km/h.\n\n🏗️ ENGINEERING: The Millau Viaduct in France (tallest bridge in the world, 343m) was designed with wind screens after Mistral gusts threatened to topple trucks. Gibraltar\'s wind patterns affect every ship entering the Mediterranean.',
                    text_de: '📍 Straße von Gibraltar — wo Atlantik auf Mittelmeer trifft\n💨 BERÜHMTE WINDE: Levante (Ost), Poniente (West), Mistral, Bora\n\n📖 Wenn Wind durch eine enge Lücke zwischen Bergen oder Küsten gezwungen wird, beschleunigt er sich — der Venturi-Effekt. Die Straße von Gibraltar (14 km breit) wirkt als natürlicher Windkanal.\n\n🌊 MISTRAL (Frankreich): Kalte Luft wird durch das Rhônetal kanalisiert und beschleunigt auf 100+ km/h. Dieser knochentrockene Wind ist so berüchtigt, dass französisches Recht ihn als Grund für vorübergehende Unzurechnungsfähigkeit anerkennt.\n\n❄️ BORA (Adria): Arktische Luft stürzt in Minuten 1.000m zur Adriaküste hinab. In Triest sind Ketten an Gehwegen installiert, an denen sich Fußgänger festhalten können.',
                    layers: ['wind']
                },
                {
                    center: [-170.0, 0.0], zoom: 3,
                    title: '🌡️ EL NIÑO — WHEN THE WIND STOPS',
                    title_de: '🌡️ EL NIÑO — WENN DER WIND AUFHÖRT',
                    text: '📍 Equatorial Pacific — ENSO oscillation zone\n🌡️ CYCLE: Every 2–7 years, lasting 12–18 months\n\n📖 El Niño ("The Christ Child," named because it often peaks around Christmas) occurs when the trade winds weaken or reverse over the equatorial Pacific. Normally, trade winds push warm water westward toward Indonesia, allowing cold nutrient-rich water to upwell off South America. When the winds fail, warm water sloshes back east, raising Pacific temperatures by 2–3°C.\n\n🌍 GLOBAL CHAOS: El Niño rewires the planet\'s weather:\n• Australia/Indonesia: Drought, catastrophic wildfires\n• Peru/Ecuador: Torrential flooding\n• India: Weak monsoon, crop failure\n• Africa: Famine in East Africa, floods in Southern Africa\n• North America: Warm winters, California storms\n\n💰 ECONOMIC IMPACT: The 1997–98 El Niño caused $35 billion in damage and 23,000 deaths worldwide. The 2015–16 event contributed to the hottest year on record at that time.\n\n🔄 LA NIÑA: The opposite phase — stronger trade winds, colder Pacific, more Atlantic hurricanes. La Niña brings drought to California and flooding to Australia. Together, El Niño and La Niña form ENSO — the planet\'s most powerful climate oscillation.',
                    text_de: '📍 Äquatorialer Pazifik — ENSO-Oszillationszone\n🌡️ ZYKLUS: Alle 2–7 Jahre, Dauer 12–18 Monate\n\n📖 El Niño („Das Christkind") tritt auf, wenn die Passatwinde über dem äquatorialen Pazifik nachlassen oder sich umkehren. Wenn die Winde versagen, schwappt warmes Wasser nach Osten zurück und erhöht die Pazifiktemperaturen um 2–3°C.\n\n🌍 GLOBALES CHAOS: El Niño verdrahtet das Wetter des Planeten neu:\n• Australien/Indonesien: Dürre, Waldbrände\n• Peru/Ecuador: Sintflutartige Überschwemmungen\n• Indien: Schwacher Monsun, Ernteausfälle\n\n💰 WIRTSCHAFTLICHER SCHADEN: El Niño 1997–98 verursachte 35 Milliarden Dollar Schaden und 23.000 Tote weltweit.',
                    layers: ['wind', 'sst'], image: { wiki: 'El_Niño', caption: 'El Niño Pacific sea surface temperature anomaly' }
                },
                {
                    center: [0.0, 10.0], zoom: 2,
                    title: '🌍 THE GLOBAL CIRCULATION — EARTH\'S HEAT ENGINE',
                    title_de: '🌍 DIE GLOBALE ZIRKULATION — DIE WÄRMEMASCHINE DER ERDE',
                    text: '📍 Global overview — atmospheric circulation cells\n🌡️ THE THREE-CELL MODEL: Hadley, Ferrel, Polar\n\n📖 Earth\'s atmosphere is a giant heat engine. The equator receives 2.5× more solar energy than the poles. Wind exists to redistribute this heat — and it does so through three pairs of circulation cells in each hemisphere:\n\n🔄 HADLEY CELL (0°–30°): Hot air rises at the equator (creating the ITCZ — Intertropical Convergence Zone, the planet\'s rainiest belt). It flows toward the poles at high altitude, cools, sinks at ~30° latitude (creating deserts — Sahara, Arabian, Australian), then returns to the equator as the trade winds.\n\n🔄 FERREL CELL (30°–60°): The mid-latitude cell where weather gets complex. Westerly winds dominate. This is where the jet stream lives and where most extratropical cyclones form.\n\n🔄 POLAR CELL (60°–90°): Cold polar air sinks at the poles, flows equatorward along the surface, and rises at ~60° (creating the polar front). When the polar vortex weakens, this cold air spills south — creating Arctic blasts.\n\n⚡ COMBINED POWER: These six cells move 5 × 10¹⁵ watts of energy — equivalent to 500,000 nuclear power plants running continuously. Without wind, the equator would be 14°C hotter and the poles 25°C colder. Wind doesn\'t just move air — it makes the planet habitable.',
                    text_de: '📍 Globale Übersicht — atmosphärische Zirkulationszellen\n🌡️ DAS DREI-ZELLEN-MODELL: Hadley, Ferrel, Polar\n\n📖 Die Erdatmosphäre ist eine riesige Wärmemaschine. Der Äquator erhält 2,5× mehr Sonnenenergie als die Pole. Wind existiert, um diese Wärme umzuverteilen — durch drei Paare von Zirkulationszellen:\n\n🔄 HADLEY-ZELLE (0°–30°): Heiße Luft steigt am Äquator auf, fließt polwärts, sinkt bei ~30° ab (erzeugt Wüsten — Sahara, Arabien, Australien) und kehrt als Passatwinde zurück.\n\n🔄 FERREL-ZELLE (30°–60°): Die Mittelbreitenzelle mit Westwinden und dem Jetstream.\n\n🔄 POLARZELLE (60°–90°): Kalte Polarluft sinkt an den Polen ab und fließt äquatorwärts.\n\n⚡ GESAMTLEISTUNG: Diese sechs Zellen bewegen 5 × 10¹⁵ Watt — äquivalent zu 500.000 Kernkraftwerken im Dauerbetrieb. Ohne Wind wäre der Äquator 14°C heißer und die Pole 25°C kälter. Wind macht den Planeten bewohnbar.',
                    layers: ['wind', 'temperature']
                }
            ]
        }
    };

    // Merge into main TOURS object when ready
    function mergeWindTours() {
        if (window._TOURS_REF) {
            Object.assign(window._TOURS_REF, WIND_TOURS);
            console.log('[tours_wind] Merged "Winds of the World" tour into TOURS');
            // Rebuild tour sites GeoJSON so new tour gets map dots
            if (typeof window._refreshTourSites === 'function') window._refreshTourSites();
        } else {
            setTimeout(mergeWindTours, 500);
        }
    }
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', () => setTimeout(mergeWindTours, 1200));
    } else {
        setTimeout(mergeWindTours, 1200);
    }
})();
